name: HTML Validation

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  validate-html:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Validate HTML files
        run: |
          find . -name "*.html" | while read file; do
            echo "Validating $file"
            npx html-validator --file="$file" --verbose --format=text || true
          done

