name: HTML Validation

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  validate-html:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Validate HTML files
        uses: w3c/actions/html-validator@v1
        with:
          files: |
            index.html
